--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JustTalDevelops/pizzaplug
build-by-default: true
branches:
- master
projects:
  pizzaplug:
    path: ""
    icon: "images/dominos.png"
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.0.0
...
